version: '3'

services:

  logstash:
    build: ./logstash
    depends_on:
      - elasticsearch
    ports:
      - "192.168.10.4:5140:5140/udp"
      - "192.168.10.4:5140:5140/tcp"
    networks:
      - elk

  elasticsearch:
    image: elasticsearch:5.5-alpine
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

networks:
  elk:
    driver: bridge
